=== Configuring Failsafe Circuit Breakers

Failsafe is a lightweight, zero-dependency library for handling failures in Java 8+,
with a concise API for handling everyday use cases and the flexibility to handle everything else.
Failsafe provides https://github.com/jhalterman/failsafe#circuit-breakers[circuit breakers] along side with
https://github.com/jhalterman/failsafe#retries[retries] and
https://github.com/jhalterman/failsafe#fallbacks[fallbacks], which can be composed
together to form policies which wrap the execution logic.

All circuit breakers will be created using the `Failsafe` and a combination of the default implementation of
https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/Fallback.java[`Fallback`],
https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicy.java[`RetryPolicy`],
https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/CircuitBreaker.java[`CircuitBreaker`] - in that order.
All these these classes can be configured using `FailsafeConfigBuilder`.

==== Default Configuration

To provide a default configuration for all of your circuit breakers create a `Customize` bean that is passed a
`FailsafeCircuitBreakerFactory`.
The `configureDefault` method can be used to provide a default configuration.

====
[source,java]
----
@Bean
public Customizer<FailsafeCircuitBreakerFactory> defaultCustomizer() {
	return factory -> factory.configureDefault(id -> new FailsafeConfigBuilder(id)
						.retryPolicy(new RetryPolicy<>().withMaxAttempts(2))
						.build());
}
----
====

==== Specific Circuit Breaker Configuration

Similarly to providing a default configuration, you can create a `Customize` bean this is passed a
`FailsafeCircuitBreakerFactory`.

====
[source,java]
----
@Bean
public Customizer<FailsafeCircuitBreakerFactory> slowCustomizer() {
	return factory -> factory.configure(
						builder -> builder
								.retryPolicy(new RetryPolicy<>().withMaxAttempts(1))
								.circuitBreaker(new net.jodah.failsafe.CircuitBreaker<>()
										.handle(Exception.class).withFailureThreshold(1)
										.withDelay(Duration.ofMinutes(1)))
								.build(),
						"slow");
----
====

In addition to configuring the circuit breaker that is created you can also customize the circuit breaker after it
has been created but before it is returned to the caller.  To do this you can use the `addFailsafeCustomizers`
method.  This can be useful for adding event handlers to the `Failsafe`.

====
[source,java]
----
@Bean
public Customizer<FailsafeCircuitBreakerFactory> slowCustomizer() {
	return factory -> factory.addFailsafeCustomizers(
						failsafe -> failsafe.onFailure(onFailureConsumer), "slow");
}
----
====
